# Generated by Django 5.1 on 2024-08-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AA_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bustype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_type', models.CharField(max_length=25)),
            ],
        ),
    ]
